export enum Resources {
    HelloWorldMessage = "Hello World!",
    HelloWorldTitle = "Hello World Title"
}

export enum FormResources {
    Basics = "Basics",
    ButtonOutputs = "Return Outputs",
    LabelParam = "Sample Label",
    Location = "Location",
    NameField = "Engine Name",
    PropsStepTextFieldLabel = "Passing static props to the component",
    PropsStepTextFieldLabelsGlobal = "TextField Validation with Global FormState",
    PropsStepTextFieldLabelsLocal = "TextField Validation with localState",
    PropsStepTextFieldLabelsValidationHook = "Adding validations to components with the useValidation Hook",
    PropsStepTextFieldSublabel1 = "Label of this textfield is set to the content of the first textfield on this step",
    PropsStepTextFieldSublabel2 = "Label of this textfield is passed as a Prop to the Form",
    PropsStepTextFieldSublabel3 = "Sublabels can either be a string or a JSX Element",
    PropsStepTitle = "Passing Props to Components",
    ResourceCreatePageBladeTitle = "Form Builder for Creates with Async Navigation",
    ResourceGroup = "Resource Group",
    ReviewStepTitle = "Review",
    SingleStepBladeTitle = "Form Builder for NonCreates with SingleStep Navigation",
    Subscription = "Subscription",
    TabsBladeTitle = "Form Builder for Non-Creates with Async Navigation",
    TextFieldLabel = "TextField",
    ValidationErrorLocationName = "East Asia",
    ValidationErrorMessageEmpty = "Value can't be empty",
    ValidationErrorMessageFooBar = "First textfield value can't be fooBar",
    ValidationErrorMessageGlobalEmpty = "Value of first textfield can't be empty",
    ValidationErrorMessageLocation = "Location name cant be East Asia",
    ValidationErrorMessageNotFooBar = "Value not fooBar",
    ValidationErrorMessageSubscription = "Subscription name cant be Home Empty Subscription",
    ValidationErrorMessageTags = "Tag Name on first row cannot be foo",
    ValidationErrorMessageTest = "Value can't be test",
    ValidationErrorSubscriptionName = "Home Empty Subscription",
    ValidationsStepTitle = "Adding validations to Forms",
    WizardBladeTitle = "Form Builder for Non-Creates with Wizard Navigation",
    WizardSampleTitle = "Wizard sample",
}
